apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalogue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-catalogue
  template:
    metadata:
      labels:
        app: product-catalogue
    spec:
      containers:
      - name: product-catalogue
        image: 7abouba/product-catalogue:latest
        ports:
        - containerPort: 5001
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/ecommerce"
---
apiVersion: v1
kind: Service
metadata:
  name: product-catalogue
spec:
  selector:
    app: product-catalogue
  ports:
  - port: 5001
    targetPort: 5001
  type: ClusterIP
