apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopfront
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopfront
  template:
    metadata:
      labels:
        app: shopfront
    spec:
      containers:
      - name: shopfront
        image: stoufaa/shopfront:latest
        ports:
        - containerPort: 5000
        env:
        - name: PRODUCT_SERVICE_URL
          value: "http://product-catalogue:5001"
        - name: STOCK_SERVICE_URL
          value: "http://stock-manager:5002"
        - name: ORDER_SERVICE_URL
          value: "http://order-management:5003"
        - name: USER_SERVICE_URL
          value: "http://user-profile:5004"
---
apiVersion: v1
kind: Service
metadata:
  name: shopfront
spec:
  selector:
    app: shopfront
  ports:
  - port: 80
    targetPort: 5000
  type: ClusterIP
